### ISSUE TITLE
Clicking on the touchpad will cause all subsequent clicks to be invalid and require a reboot

### ISSUE THREAD

**Issue by JY-DB** [Sniki/Lenovo-Thinkpad-X240#4] opened 2020-08-24 04:21 UTC
Clicking on the touchpad will cause all subsequent clicks to be invalid and require a reboot
I currently use a wireless mouse
Thank you very much

(My english is not good, sorry)

**Comment by Sniki** [comment] 2020-08-24 07:43
> Clicking on the touchpad will cause all subsequent clicks to be invalid and require a reboot
> I currently use a wireless mouse
> Thank you very much
> 
> (My english is not good, sorry)

Not sure if I understand the context of the problem.
So if a mouse is used (Wireless or USB) the touchpad clicks won’t work, is that what you meant ?

**Comment by JY-DB** [comment] 2020-08-24 10:13
It should be said that as long as the touchpad is pressed and clicked once, subsequent clicks will fail. Regardless of whether the wireless mouse is used or not, all objects cannot be selected. You must turn off the power button for three seconds to call the power menu and use the keyboard to select shutdown

**Comment by Silfalion** [comment] 2020-09-07 19:23
Have the same issue, maybe bc of the new Vodoo RMI.

**Comment by varszegimarcell** [comment] 2020-10-15 20:21
I have the same issue too. 

When you click with the touchpad, the click somehow get stuck, and you not able to do anything with the mouse untill a reboot. It's pretty annoying. The click happpens, but the OS behaves as you would never release the left button.

**Comment by Silfalion** [comment] 2020-10-15 20:33
It is. For now the workaround I found is to take the 0.6.0 version and to update the kext and opencore to 0.6.2 without using the new voodoo kext.

**Comment by varszegimarcell** [comment] 2020-10-15 23:48
> It is. For now the workaround I found is to take the 0.6.0 version and to update the kext and opencore to 0.6.2 without using the new voodoo kext.

What version of voodooRMI.kext are you using?

**Comment by Silfalion** [comment] 2020-10-17 09:08
Not using it actually. I plan to soon when redoing my EFI. Is there a lot of improvement compared to the previous kexts?

**Comment by varszegimarcell** [comment] 2020-10-17 21:13
> 
> 
> Not using it actually. I plan to soon when redoing my EFI. Is there a lot of improvement compared to the previous kexts?

Well, as far as I can tell, nothing have been changed. When I click the touchpad, the click still stucks, and never releases. 

My workaround for the moment is that I setted Settings -> Trackpad -> Tap to Click, and I have to remember not to click the trackpad, or I have to reboot. With tap to click, no issues found at the moment, other than the 3 finger gestures does not work, and as far as I remember, 3 fingers are the upper limit for this touchpad.

**Comment by Sniki** [comment] 2020-10-18 08:13
This problem may be with the standard touchpad, i did replace it with the clickpad from X250 that does have physical buttons.

Not a single issue ever happened with it.
All gestures are working flawlessly (better than with VoodooPS2) and no such issues as reported.

The reason why I didn’t update my ThinkPad Projects is because they are fine and stable as they are right now and I didn’t have much time lately and not just that but some major changes are coming which im waiting for them to be complete and ready for daily usage.

That is AirportItlwm.kext, YogaSMC, battery reading support without a single patch at all.
Just an SSDT for that.

- Perfect Touchpad functionality
- Improved Performance and Power Management
- Native Apple OSD keyboard function keys etc like brightness Apple native HUD and others.
- Battery conservation mode and other Lenovo functions that are available on Windows, are coming on macOS.
Etc

**Comment by varszegimarcell** [comment] 2020-10-19 11:07
> This problem may be with the standard touchpad, i did replace it with the clickpad from X250 that does have physical buttons.
> 
> Not a single issue ever happened with it.
> All gestures are working flawlessly (better than with VoodooPS2) and no such issues as reported.
> 
> The reason why I didn’t update my ThinkPad Projects is because they are fine and stable as they are right now and I didn’t have much time lately and not just that but some major changes are coming which im waiting for them to be complete and ready for daily usage.
> 
> That is AirportItlwm.kext, YogaSMC, battery reading support without a single patch at all.
> Just an SSDT for that.
> 
> * Perfect Touchpad functionality
> * Improved Performance and Power Management
> * Native Apple OSD keyboard function keys etc like brightness Apple native HUD and others.
> * Battery conservation mode and other Lenovo functions that are available on Windows, are coming on macOS.
>   Etc

I can confirm, that I have the original, factory stock X240 touchpad, and that’s where the click can stuck if you press down the corner of the trackpad. 

The stock touchpad design is pretty annoying, maybe I will replace mine too. Do any BIOS modifications needed for that? (No whitelists removed on my laptop.)

I’ve been experimenting with AirportItlwm.kext after I’ve been updated to OpenCore 0.6.2, but I had no luck with it.

Looking forward to the update! :D

**Comment by Silfalion** [comment] 2020-10-19 11:11
The airportitlwm started to work for me after I deleted all the file in the SystemConfiguration(check the help) except for the ending in .boot but I wasn't informed it may not be safe bc icloud accounts are linked to it.

It you're gonna try this, don't forget to empty the bin after deleting. Had the problem for 3 months and now it works. No crazy speeds but it works.

**Comment by Silfalion** [comment] 2020-10-19 11:11
> This problem may be with the standard touchpad, i did replace it with the clickpad from X250 that does have physical buttons.
> 
> 
> 
> Not a single issue ever happened with it.
> 
> All gestures are working flawlessly (better than with VoodooPS2) and no such issues as reported.
> 
> 
> 
> The reason why I didn’t update my ThinkPad Projects is because they are fine and stable as they are right now and I didn’t have much time lately and not just that but some major changes are coming which im waiting for them to be complete and ready for daily usage.
> 
> 
> 
> That is AirportItlwm.kext, YogaSMC, battery reading support without a single patch at all.
> 
> Just an SSDT for that.
> 
> 
> 
> - Perfect Touchpad functionality
> 
> - Improved Performance and Power Management
> 
> - Native Apple OSD keyboard function keys etc like brightness Apple native HUD and others.
> 
> - Battery conservation mode and other Lenovo functions that are available on Windows, are coming on macOS.
> 
> Etc

Very excited about those. Thanks again for your work.

**Comment by lunadiotic** [comment] 2020-12-20 03:30
So, is there a solution to this without physically changing the touchpad?

**Comment by lunadiotic** [comment] 2020-12-21 18:31
Here I just enable three fingers for dragging
It's more impressive exp I guess
and never clicked my trackpad anymore

https://support.apple.com/en-us/HT204609

**Comment by Sniki** [comment] 2021-03-21 13:52
To be fixed in master today

**Closed as completed by Sniki** 2021-03-21 13:52 UTC
